-- lua/plugins/css-templates.lua
-- Generador de templates CSS para desarrollo rápido

return {
	{
		"nvim-lua/plenary.nvim",
		config = function()
			-- Función para crear template CSS básico
			local function create_css_template(template_type)
				local templates = {
					reset = {
						"/* CSS Reset */",
						"* {",
						"    margin: 0;",
						"    padding: 0;",
						"    box-sizing: border-box;",
						"}",
						"",
						"body {",
						"    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;",
						"    line-height: 1.6;",
						"    color: #333;",
						"}",
						"",
						"img {",
						"    max-width: 100%;",
						"    height: auto;",
						"}",
						"",
						"a {",
						"    text-decoration: none;",
						"    color: inherit;",
						"}",
					},
					flexbox = {
						"/* Flexbox Utilities */",
						".flex {",
						"    display: flex;",
						"}",
						"",
						".flex-center {",
						"    display: flex;",
						"    justify-content: center;",
						"    align-items: center;",
						"}",
						"",
						".flex-between {",
						"    display: flex;",
						"    justify-content: space-between;",
						"    align-items: center;",
						"}",
						"",
						".flex-col {",
						"    display: flex;",
						"    flex-direction: column;",
						"}",
						"",
						".flex-wrap {",
						"    flex-wrap: wrap;",
						"}",
					},
					grid = {
						"/* CSS Grid Utilities */",
						".grid {",
						"    display: grid;",
						"}",
						"",
						".grid-2 {",
						"    display: grid;",
						"    grid-template-columns: repeat(2, 1fr);",
						"    gap: 1rem;",
						"}",
						"",
						".grid-3 {",
						"    display: grid;",
						"    grid-template-columns: repeat(3, 1fr);",
						"    gap: 1rem;",
						"}",
						"",
						".grid-auto {",
						"    display: grid;",
						"    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));",
						"    gap: 1rem;",
						"}",
					},
					responsive = {
						"/* Responsive Design */",
						":root {",
						"    --container-max-width: 1200px;",
						"    --spacing-xs: 0.25rem;",
						"    --spacing-sm: 0.5rem;",
						"    --spacing-md: 1rem;",
						"    --spacing-lg: 2rem;",
						"    --spacing-xl: 4rem;",
						"}",
						"",
						".container {",
						"    max-width: var(--container-max-width);",
						"    margin: 0 auto;",
						"    padding: 0 var(--spacing-md);",
						"}",
						"",
						"/* Mobile First */",
						"@media (min-width: 768px) {",
						"    .container {",
						"        padding: 0 var(--spacing-lg);",
						"    }",
						"}",
						"",
						"@media (min-width: 1024px) {",
						"    .container {",
						"        padding: 0 var(--spacing-xl);",
						"    }",
						"}",
					},
					components = {
						"/* Component Styles */",
						".btn {",
						"    display: inline-block;",
						"    padding: 0.75rem 1.5rem;",
						"    border: none;",
						"    border-radius: 0.375rem;",
						"    background: #3b82f6;",
						"    color: white;",
						"    font-weight: 500;",
						"    text-align: center;",
						"    cursor: pointer;",
						"    transition: all 0.3s ease;",
						"}",
						"",
						".btn:hover {",
						"    background: #2563eb;",
						"    transform: translateY(-2px);",
						"    box-shadow: 0 4px 12px rgba(59, 130, 246, 0.4);",
						"}",
						"",
						".card {",
						"    background: white;",
						"    border-radius: 0.5rem;",
						"    padding: 1.5rem;",
						"    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);",
						"    transition: box-shadow 0.3s ease;",
						"}",
						"",
						".card:hover {",
						"    box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);",
						"}",
					},
					animations = {
						"/* Animations */",
						"@keyframes fadeIn {",
						"    from { opacity: 0; }",
						"    to { opacity: 1; }",
						"}",
						"",
						"@keyframes slideIn {",
						"    from {",
						"        opacity: 0;",
						"        transform: translateY(20px);",
						"    }",
						"    to {",
						"        opacity: 1;",
						"        transform: translateY(0);",
						"    }",
						"}",
						"",
						"@keyframes pulse {",
						"    0%, 100% { opacity: 1; }",
						"    50% { opacity: 0.5; }",
						"}",
						"",
						".fade-in {",
						"    animation: fadeIn 0.6s ease-out;",
						"}",
						"",
						".slide-in {",
						"    animation: slideIn 0.6s ease-out;",
						"}",
						"",
						".pulse {",
						"    animation: pulse 2s infinite;",
						"}",
					},
				}

				if templates[template_type] then
					vim.api.nvim_put(templates[template_type], "l", true, true)
					print("✅ Template CSS '" .. template_type .. "' insertado")
				else
					print("❌ Template no encontrado: " .. template_type)
				end
			end

			-- Comando para insertar templates
			vim.api.nvim_create_user_command("CSSTemplate", function(opts)
				local template = opts.args ~= "" and opts.args or "reset"
				create_css_template(template)
			end, {
				nargs = "?",
				complete = function()
					return { "reset", "flexbox", "grid", "responsive", "components", "animations" }
				end,
				desc = "Insertar template CSS (reset, flexbox, grid, responsive, components, animations)",
			})

			-- Función para crear archivo CSS completo
			local function create_complete_css_file(filename)
				local complete_css = {
					"/* ===== CSS RESET ===== */",
					"* {",
					"    margin: 0;",
					"    padding: 0;",
					"    box-sizing: border-box;",
					"}",
					"",
					"/* ===== VARIABLES CSS ===== */",
					":root {",
					"    /* Colors */",
					"    --primary-color: #3b82f6;",
					"    --secondary-color: #64748b;",
					"    --success-color: #10b981;",
					"    --warning-color: #f59e0b;",
					"    --error-color: #ef4444;",
					"    --text-color: #1f2937;",
					"    --bg-color: #ffffff;",
					"    --border-color: #e5e7eb;",
					"",
					"    /* Spacing */",
					"    --spacing-xs: 0.25rem;",
					"    --spacing-sm: 0.5rem;",
					"    --spacing-md: 1rem;",
					"    --spacing-lg: 2rem;",
					"    --spacing-xl: 4rem;",
					"",
					"    /* Typography */",
					"    --font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;",
					"    --font-size-sm: 0.875rem;",
					"    --font-size-base: 1rem;",
					"    --font-size-lg: 1.125rem;",
					"    --font-size-xl: 1.25rem;",
					"    --font-size-2xl: 1.5rem;",
					"    --font-size-3xl: 2rem;",
					"",
					"    /* Border Radius */",
					"    --radius-sm: 0.25rem;",
					"    --radius-md: 0.375rem;",
					"    --radius-lg: 0.5rem;",
					"    --radius-full: 9999px;",
					"",
					"    /* Shadows */",
					"    --shadow-sm: 0 1px 2px rgba(0, 0, 0, 0.05);",
					"    --shadow-md: 0 4px 6px rgba(0, 0, 0, 0.1);",
					"    --shadow-lg: 0 10px 15px rgba(0, 0, 0, 0.1);",
					"    --shadow-xl: 0 20px 25px rgba(0, 0, 0, 0.1);",
					"}",
					"",
					"/* ===== BASE STYLES ===== */",
					"body {",
					"    font-family: var(--font-family);",
					"    font-size: var(--font-size-base);",
					"    line-height: 1.6;",
					"    color: var(--text-color);",
					"    background-color: var(--bg-color);",
					"}",
					"",
					"img {",
					"    max-width: 100%;",
					"    height: auto;",
					"}",
					"",
					"a {",
					"    color: var(--primary-color);",
					"    text-decoration: none;",
					"}",
					"",
					"a:hover {",
					"    text-decoration: underline;",
					"}",
